---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coaxial.transmission"
      ansible.builtin.include_role:
        name: "coaxial.transmission"

    - name: Install curl (tests requirement)
      ansible.builtin.package:
        name: curl
        state: present
